### ISSUE TITLE
some information required on platform supported for the rust build

### ISSUE THREAD

**Issue by stuzenz** [ha-shine/wasm-tetris#1]
Hi, thanks for sharing your code. This is just an FYI (I understand this was just a project for learning rust/web vs. something you are looking at supporting across platforms etc. 

Thanks again for sharing.

The following error came out on cargo build on macos (version 10.15.3)

```
➜ cargo build
warning: Found `debug_assertions` in `target.'cfg(...)'.dependencies`. This value is not supported for selecting dependencies and will not work as expected. To learn more visit https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

Compiling tetris-rs v0.1.0 (/Users/stuart/Development/2020/03-March/wasm-tetris/rust)
error[E0433]: failed to resolve: use of undeclared type or module `console_error_panic_hook`
  --> src/lib.rs:26:9
   |
26 |         console_error_panic_hook::set_once();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `console_error_panic_hook`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `tetris-rs`.

To learn more, run the command again with --verbose.
```

**Comment by ha-shine** [comment]
That is strange because I tested this on Mac too. Have you installed `wasm-pack` (`cargo install wasm-pack`)? Though I'm not sure that's the problem.
